version: '3'
services:
  wise-api:
    build:
      context: ./wise-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product
#      SPRING_DATASOURCE_USERNAME: product_user
#      SPRING_DATASOURCE_PASSWORD: product_user_password

  react-app:
    build:
      context: ./wise-ui
      dockerfile: Dockerfile
    depends_on:
      - wise-api
    ports:
      - "80:80"