# SpringBoot Configuration ...

spring:
  mail:
    host: smtp.example.com
    port: 25
    username: setusername
    password: setpassword
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  output:
    ansi:
      enabled=always:
  application:
    name: wisemapping-api
    title: wisemapping-api
  datasource:
    url: jdbc:hsqldb:mem:wisemapping
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    password: ''
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        current_session_context_class: thread
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
      platform: hsqldb

# Login ...
logging:
  level:
    org:
      apache:
        tomcat: INFO
    root: TRACE

# Application Configuration.
app:
  jwt:
    secret: dlqxKAg685SaKhsQXIMeM=JWCw3bkl3Ei3Tb7LMlnd19oMd66burPNlJ0Po1qguyjgpakQTk2CN3
    expirationMin: 10080 # One week
  admin:
    user: admin@wisemapping.org
  mail:
    serverSendEmail: root@localhost
    supportEmail: root@localhost
#  accounts:
#    exclusion:
#      domain:






google:
  ads:
    enabled: false
  analytics:
    account: UA-XXXX
    enabled: false
  recaptcha2:
    enabled: true
    secretKey: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    siteKey: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
security:
  oauth2:
    google:
      confirmUrl: https://oauth2.googleapis.com/token
      url: https//review
      userinfoUrl: https://www.googleapis.com/oauth2/v3/userinfo
site:
  homepage: c/login
  static:
    js:
      url: /static


